# export http_proxy="localhost:8889"
# export https_proxy="localhost:8889"
# echo "http_proxy:"$http_proxy "https_proxy:"$https_proxy
module_path+=( "/home/kyle/.zinit/bin/zmodules/Src" )
zmodload zdharma/zplugin
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 当没有zinit时自动安装下载
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
		print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
		command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
		command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
				print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
				print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# 设置Powerlevel10k
# zinit ice wait'!' 
# zinit load spaceship-prompt/spaceship-prompt
zinit ice lucid depth=1 nocd \
    atload'_p9k_do_nothing'
zinit light romkatv/powerlevel10k 

# 加载 Oh-My-Zsh 框架及部分插件
zinit lucid wait for                                        \
OMZ::lib/completion.zsh                                     \
OMZ::lib/key-bindings.zsh                                   \
OMZ::lib/theme-and-appearance.zsh                           \
OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh \
OMZ::plugins/sudo/sudo.plugin.zsh                           \
OMZ::plugins/autojump/autojump.plugin.zsh                   \
zsh-users/zsh-completions                                   \
hlissner/zsh-autopair                                       \

zinit ice lucid wait='0' svn
zinit snippet OMZ::plugins/extract

zinit ice lucid wait='1'
zinit snippet OMZ::plugins/git/git.plugin.zsh

# zinit snippet https://mimosa-pudica.net/src/incr-0.2.zsh

zinit snippet OMZ::lib/history.zsh

zinit ice lucid wait='0' atinit='zpcompinit'
zinit light zdharma/fast-syntax-highlighting

zinit ice lucid wait="0" atload='_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# 基本操作
export PATH=$HOME/bin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:$PATH
export EDITOR='nvim'
export RANGER_LOAD_DEFAULT_RC=FALSE

# eval $(thefuck --alias)

# FZF
export FZF_DEFAULT_OPTS='--bind ctrl-e:down,ctrl-u:up --preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_COMPLETION_TRIGGER='\'
export FZF_TMUX_HEIGHT='80%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'

# 别名
alias c='clear'
alias ll='ls -lh'
alias la='ll -a'
alias lr='la -R'
alias vi='vim'
alias l='ls -a'
alias javac="javac -J-Dfile.encoding=utf8"
alias grep="grep --color=auto"
alias -s html=nvim
alias -s rb=nvim
alias -s py=nvim
alias -s js=nvim
alias -s c=nvim
alias -s java=nvim
alias -s txt=nvim
alias s='neofetch | lolcat -F 0.3'
alias pip3sp="sudo -H pip3 --proxy localhost:1081"
alias pip3p="pip3 --proxy localhost:1081"
alias aptp="sudo apt -c ~/.apt.conf"
alias hp='export http_proxy="localhost:8889"
export https_proxy="localhost:8889"
echo "http_proxy:"$http_proxy "https_proxy:"$https_proxy'
alias jlog='journalctl -f -o short -u'
alias h='history -ir -10'
alias mv='mv -i'
alias x='extract'
alias rename='perl-rename'
alias vim='nvim'
alias mp='mkdir -p'
alias ra='ranger'
alias rm -rf='rm -i'
alias lg='lazygit'
alias pacupdate='~/.local/bin/pacupdate'
alias clean='sudo pacman -R $(pacman -Qdtq)'


# 在启动时pfetch
# pfetch

# Powerlevel10k设置
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
