# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Created by newuser for 5.8

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk
# export http_proxy="localhost:8889"
# export https_proxy="localhost:8889"
# echo "http_proxy:"$http_proxy "https_proxy:"$https_proxy

# BasicExport
export PATH=$HOME/bin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:$PATH
export EDITOR='nvim'
export RANGER_LOAD_DEFAULT_RC=FALSE

# FZF
export FZF_DEFAULT_OPTS='--bind ctrl-e:down,ctrl-u:up --preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
# export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_COMPLETION_TRIGGER='\'
export FZF_TMUX_HEIGHT='80%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'

# The Fuck
eval $(thefuck --alias)
eval $(thefuck --alias FUCK)

# KeyBindings
alias c='clear'
alias ls='exa'
alias ll='ls -lh'
alias la='ll -a'
alias lr='la -R'
alias vi='vim'
alias l='ls -a'
alias javac="javac -J-Dfile.encoding=utf8"
alias grep="grep --color=auto"
alias -s html=nvim
alias -s rb=nvim
alias -s py=nvim
alias -s js=nvim
alias -s c=nvim
alias -s java=nvim
alias -s txt=nvim
alias s='neofetch|lolcat'
alias pip3sp="sudo -H pip3 --proxy localhost:1081"
alias pip3p="pip3 --proxy localhost:1081"
alias aptp="sudo apt -c ~/.apt.conf"
alias hp='export http_proxy="localhost:8889"
export https_proxy="localhost:8889"
echo "http_proxy:"$http_proxy "https_proxy:"$https_proxy'
alias jlog='journalctl -f -o short -u'
alias h='history -ir -10'
alias mv='mv -i'
alias x='extract'
alias rename='perl-rename'
alias vim='nvim'
alias mp='mkdir -p'
alias ra='ranger'
alias rm -rf='rm -i'
alias lg='lazygit'
alias pacupdate='~/.local/bin/pacupdate'
alias clean='sudo pacman -R $(pacman -Qdtq)'

# Pacman
zinit ice lucid wait='0' atload='_zsh_autosuggest_start'; zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit ice lucid wait='0'; zinit snippet OMZL::key-bindings.zsh
zinit ice lucid wait='0'; zinit snippet OMZL::git.zsh
zinit ice lucid wait='0'; zinit snippet OMZL::history.zsh
zinit ice lucid wait='0'; zinit snippet OMZP::autojump/autojump.plugin.zsh
zinit ice lucid wait='0'; zinit snippet OMZP::colored-man-pages/colored-man-pages.plugin.zsh
zinit ice lucid wait='0'; zinit snippet OMZP::archlinux/archlinux.plugin.zsh
zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit load zsh-users/zsh-completions
zinit snippet OMZL::completion.zsh

# InitCompletion
autoload -Uz compinit; compinit; zinit cdreplay -q

# ShowOnStartup
pfetch

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
