# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export EDITOR='nvim'

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# FZF
# source ~/.config/zsh/fzf.zsh
export FZF_DEFAULT_OPTS='--bind ctrl-e:down,ctrl-u:up --preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
# export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_COMPLETION_TRIGGER='\'
export FZF_TMUX_HEIGHT='80%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'
source ~/.config/zsh/key-bindings.zsh
source ~/.config/zsh/completion.zsh

# Ibus配置
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
#
# The Fuck
eval $(thefuck --alias)
eval $(thefuck --alias FUCK)

plugins=(
	autojump
	zsh-syntax-highlighting
	git
	zsh-autosuggestions
	extract
	colored-man-pages
	cp
	zsh-completions
)
source $ZSH/oh-my-zsh.sh
. /etc/profile.d/autojump.zsh

if [[ $(ps --no-header -p $PPID -o comm) =~ '^yakuake|konsole$' ]]; then
	for wid in $(xdotool search --pid $PPID); do
		xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
if [ "$(tty)" = "/dev/tty1" ]; then
	export LC_ALL="en_US.UTF-8"
	export LANGUAGE="en_US.UTF-8"
	export LANG="en_US.UTF-8"
fi
if [ "$(tty)" = "/dev/tty2" ]; then
	export LC_ALL="en_US.UTF-8"
	export LANGUAGE="en_US.UTF-8"
	export LANG="en_US.UTF-8"
fi
alias c='echo && clear'
alias ll='ls -lh'
alias la='ll -a'
alias lr='la -R'
alias vi='vim'
alias l='ls -a'
alias javac="javac -J-Dfile.encoding=utf8"
alias grep="grep --color=auto"
alias -s html=nvim
alias -s rb=nvim
alias -s py=nvim
alias -s js=nvim
alias -s c=nvim
alias -s java=nvim
alias -s txt=nvim
alias s='neofetch|lolcat'

alias pip3sp="sudo -H pip3 --proxy localhost:1081"
alias pip3p="pip3 --proxy localhost:1081"
alias aptp="sudo apt -c ~/.apt.conf"

alias hp='export http_proxy="localhost:8889"
export https_proxy="localhost:8889"
echo "http_proxy:"$http_proxy "https_proxy:"$https_proxy'
# alias hpw='export http_proxy="coreja.com:1082"
# export https_proxy="coreja.com:1082"
# echo "http_proxy:"$http_proxy "https_proxy:"$https_proxy'
# alias np='export http_proxy="" export https_proxy=""
# echo "http_proxy:"$http_proxy "https_proxy "$https_proxy'
#
# alias ghp='git config --global http.proxy "localhost:1081"
# git config --global http.proxy'
# alias gnp='git config --global http.proxy ""
# git config --global http.proxy'

alias jlog='journalctl -f -o short -u'
alias h='history -ir -10'
alias mv='mv -i'
alias x='extract'
alias rename='perl-rename'
alias vim='nvim'
alias mp='mkdir -p'
alias ra='ranger'
alias rm -rf='rm -i'
alias lg='lazygit'
alias pacupdate='~/.local/bin/pacupdate'
alias clean='sudo pacman -R $(pacman -Qdtq)'
fortune|cowsay|lolcat


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"
